using System;
using NUnit.Framework;

namespace Challenge2
{
    [TestFixture]
    public class Challenge2
    {
        // Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
        // By starting with 1 and 2, the first 10 terms will be:
        // 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
        //
        // By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
        // find the sum of the even-valued terms.
        
        public class Fibonacci
        {
            private int sum;

            private void sumevens()
            {
                int one = 1;
                int two = 2;

                sum = 0;
                while (two <= 4000000)
                {
                    if (two % 2 == 0) // even
                    {
                        sum += two;
                    }

                    int next = one + two;
                    one = two;
                    two = next;
                };
            }

            public void calctotal()
            {
                sumevens();
                Console.WriteLine("Sum is {0}", sum);
            }
        }

        [Test]
        public void fibotest()
        {
            Fibonacci fib = new Fibonacci();
            fib.calctotal();
        }
    }
}